name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: honyua/jupyterlab:laster
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

  test:
    needs: build
    runs-on: ubuntu-latest
    container: 
      image: honyua/jupyter:laster
      ports:
        - 8080:8888
      volumes:
        - /root/jupyter:/root
        - /var/run/docker.sock:/var/run/docker.sock
        - /usr/bin/docker:/usr/bin/docker
      options: --privileged
      
    
